config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "campaigns#index"
  resources :campaigns, only: [:index, :show] do
    resources :candidates, only: [:index, :show]
    resources :votes, only: [:index, :show]
  end
  post '/import_votes', to: 'campaigns#import_votes'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_and_belongs_to_many :candidates
  has_many :votes
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :campaign
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :candidate
  belongs_to :campaign
end

app/models/vote_count.rb
class VoteCount < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show]
  def index
    @campaigns = Campaign.all
    @invalid_votes = VoteCount.last&.invalid_vote
  end

  def show; end

  def import_votes
    # I thought it will be a nice addition to be able to upload the file through the form
    file = params[:file]
    file_path = file.tempfile.path
    if file.content_type != 'text/plain'
      flash[:error] = 'Only text files (.txt) are allowed.'
      redirect_to campaign_path(params[:id])
      return
    end

    VoteImport.new.import_log_data(file_path)
    total_votes = VoteImport.new.count_lines(file_path)
    VoteCount.create!(valid_vote: (Vote.count.to_s), invalid_vote: (total_votes - Vote.count).to_s)

    redirect_to root_path
  end
  private

  def set_campaign
    @campaign = Campaign.find(params[:id])
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    @candidates = Candidate.all
  end

  def show
    @candidate = Candidate.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/campaigns/index.html.erb
<h1>Campaigns</h1>
<% if flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>
<% if Vote.count == 0 %>
  <%= form_with(url: import_votes_path, method: :post, local: true, multipart: true) do |form| %>
    <%= form.file_field :file %>
    <%= form.submit 'Import Votes' %>
  <% end %>
<% end %>
 <h2>Invalid Votes: <%= @invalid_votes %></h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= link_to campaign.name, campaign_path(campaign)  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/campaigns/show.html.erb
<h1><%= @campaign.name %></h1>
<h2>Invalid Votes: <%= @campaign.votes.where.not(validity: "during")&.count %></h2>
<% candidates = Candidate.where(campaign_id: @campaign.id) %>
<% candidates.each do |candidate|  %>

  <p>Candidate name: <%= candidate.name %></p>
  <p>Votes: <%= candidate.votes.where(validity: "during")&.count %></p>
  <br>
<% end %>
<%=  %>
<table>
  <thead>
    <tr>
      <th>Choice</th>
      <th>Validity</th>
      <th>Message</th>
    </tr>
  </thead>
  <tbody>
    <% @campaign.votes.each do |vote| %>
      <tr>
      <%# to be fixed, it's shownig wrong campaign assigned to the candidate %>
        <td><p><%= vote.choice %></p></td>
        <td><p><%= vote.validity %> </p></td>
        <td><p><%= vote.msisdn %> </p></td>
      </tr>
    <% end %>
  </tbody>

app/views/candidates/index.html.erb
<h1>Candidates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Score</th>
      <th>Messages </th>
    </tr>
  </thead>
  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= link_to candidate.name, campaign_candidate_path(candidate.campaign, candidate) %></td>
        <td><%= candidate.votes.count  %></td>
        <td><%= @failed_votes %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/candidates/show.html.erb
<h1><%= @candidate.name %></h1>

<p>Name: <%= @candidate.name %></p>
<p>Campaign Name: <%= Campaign.find(@candidate.campaign_id).name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TVSms</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= link_to "Campaigns", root_path %>
    <%= yield %>
  </body>
</html>